_target_: src.datamodules.mnist_small_tgt_val_adapt_datamodule.MnistSmallTgtValAdaptDataModule

data_dir: ${data_dir}/mnist_adapt/ # data_dir is specified in config.yaml
batch_size: 32
num_workers: 0
pin_memory: False
adapt: False